// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: WindowHintClientApi.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Graphics.Windowing.Api.GlfwApi.Enums;

public enum WindowHintClientApi
{
    ClientApi = 0x00022001,
}