// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: GamepadAxis.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Graphics.Api.GlfwApi.Enums;

public enum GamepadAxis
{
    LeftX = 0,
    LeftY = 1,
    RightX = 2,
    RightY = 3,
    LeftTrigger = 4,
    RightTrigger = 5,
    Last = RightTrigger,
}