// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: ClientApi.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.GraphicsApi.GlfwApi.Enums;

public enum ClientApi
{
    NoApi = 0,
    OpenglApi = 0x00030001,
    OpenglEsApi = 0x00030002,
}