// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: GamepadButton.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.GraphicsApi.GlfwApi.Enums;

public enum GamepadButton
{
    Centered = 0,
    Up = 1,
    Right = 2,
    Down = 4,
    Left = 8,
    RightUp = (Right | Up),
    RightDown = (Right | Down),
    LeftUp = (Left  | Up),
    LeftDown = (Left  | Down),
}