// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: KeyModifier.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Rendering.Graphics.Api.GlfwApi.Enums;

public enum KeyModifier
{
    Shift = 0x0001,
    Control = 0x0002,
    Alt = 0x0004,
    Super = 0x0008,
    CapsLock = 0x0010,
    NumLock = 0x0020,
}