// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: MouseButton.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Rendering.Graphics.Api.GlfwApi.Enums;

public enum MouseButton
{
    Button1 = 0,
    Button2 = 1,
    Button3 = 2,
    Button4 = 3,
    Button5 = 4,
    Button6 = 5,
    Button7 = 6,
    Button8 = 7,
    Last = Button8,
    Left = Button1,
    Right = Button2,
    Middle = Button3,
}