// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: WindowHintString.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Rendering.Graphics.Api.GlfwApi.Enums;

public enum WindowHintString
{
    CocoaFrameName = 0x00023002,
    X11ClassName = 0x00024001,
    X11InstanceName = 0x00024002,
    WaylandAppId = 0x00026001,
}