// ------------------------------------------------------------------------------
// This code was generated by a Hypercube.Generators
// File: glfw3.h
// Path: WindowHintBool.g.cs
// ------------------------------------------------------------------------------

namespace Hypercube.Core.Rendering.Graphics.Api.GlfwApi.Enums;

public enum WindowHintBool
{
    Focused = 0x00020001,
    Iconified = 0x00020002,
    Resizable = 0x00020003,
    Visible = 0x00020004,
    Decorated = 0x00020005,
    AutoIconify = 0x00020006,
    Floating = 0x00020007,
    Maximized = 0x00020008,
    CenterCursor = 0x00020009,
    Hovered = 0x0002000B,
    FocusOnShow = 0x0002000C,
    Stereo = 0x0002100C,
    SrgbCapable = 0x0002100E,
    OpenglForwardCompat = 0x00022006,
    OpenglDebugContext = 0x00022007,
    ContextNoError = 0x0002200A,
    ScaleToMonitor = 0x0002200C,
    ScaleFramebuffer = 0x0002200D,
}